[metadata]
name = py4godot-stubs
version = 4.7.0
description = Type stubs for py4godot
author = py4godot contributors
license = MIT
requires-python = >=3.12

[options]
packages = find_namespace:
install_requires = 
    py4godot

[options.packages.find]
include = py4godot*

[options.package_data]
py4godot = *.pyi
